package MeditorPersistence;
// Generated Apr 29, 2016 4:36:30 PM by Hibernate Tools 4.3.1



/**
 * Admin generated by hbm2java
 */
public class Admin extends User  implements java.io.Serializable {


     private Integer id;
     private int accessLevel;

    public Admin() {
    }

    public Admin(int accessLevel) {
       this.accessLevel = accessLevel;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    public int getAccessLevel() {
        return this.accessLevel;
    }
    
    public void setAccessLevel(int accessLevel) {
        this.accessLevel = accessLevel;
    }

}


