package MeditorPersistence;
// Generated Apr 29, 2016 4:36:30 PM by Hibernate Tools 4.3.1



/**
 * City generated by hbm2java
 */
public class City  implements java.io.Serializable {


     private Integer id;
     private String cityName;
     private Integer geoId;

    public City() {
    }

    public City(String cityName, Integer geoId) {
       this.cityName = cityName;
       this.geoId = geoId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }
    public Integer getGeoId() {
        return this.geoId;
    }
    
    public void setGeoId(Integer geoId) {
        this.geoId = geoId;
    }




}


