package MeditorPersistence;
// Generated Apr 29, 2016 4:36:30 PM by Hibernate Tools 4.3.1



/**
 * Cycle generated by hbm2java
 */
public class Cycle  implements java.io.Serializable {


     private Integer id;
     private String cycle;

    public Cycle() {
    }

    public Cycle(String cycle) {
       this.cycle = cycle;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCycle() {
        return this.cycle;
    }
    
    public void setCycle(String cycle) {
        this.cycle = cycle;
    }




}


