package MeditorPersistence;
// Generated Apr 29, 2016 4:36:30 PM by Hibernate Tools 4.3.1



/**
 * Doctor generated by hbm2java
 */
public class Doctor  implements java.io.Serializable {


     private Integer id;
     private Integer assignedVstId;
     private Integer createdFrom;
     private String name;
     private Integer specialtyId;
     private String address;
     private String phone;
     private Integer cityId;
     private Integer geoAreaId;
     private Integer institutionId;
     private String position;
     private String assignedVstName;
     private String specialtyName;
     private String cityName;
     private String geoAreaName;
     private String institutionName;

    public Doctor() {
    }

    public Doctor(Integer assignedVstId, Integer createdFrom, String name, Integer specialtyId, String address, String phone, Integer cityId, Integer geoAreaId, Integer institutionId, String position) {
       this.assignedVstId = assignedVstId;
       this.createdFrom = createdFrom;
       this.name = name;
       this.specialtyId = specialtyId;
       this.address = address;
       this.phone = phone;
       this.cityId = cityId;
       this.geoAreaId = geoAreaId;
       this.institutionId = institutionId;
       this.position = position;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getAssignedVstId() {
        return this.assignedVstId;
    }
    
    public void setAssignedVstId(Integer assignedVstId) {
        this.assignedVstId = assignedVstId;
    }
    public Integer getCreatedFrom() {
        return this.createdFrom;
    }
    
    public void setCreatedFrom(Integer createdFrom) {
        this.createdFrom = createdFrom;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getSpecialtyId() {
        return this.specialtyId;
    }
    
    public void setSpecialtyId(Integer specialtyId) {
        this.specialtyId = specialtyId;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Integer getCityId() {
        return this.cityId;
    }
    
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }
    public Integer getGeoAreaId() {
        return this.geoAreaId;
    }
    
    public void setGeoAreaId(Integer geoAreaId) {
        this.geoAreaId = geoAreaId;
    }
    public Integer getInstitutionId() {
        return this.institutionId;
    }
    
    public void setInstitutionId(Integer institutionId) {
        this.institutionId = institutionId;
    }
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }
    
    public String getAssignedVstName() {
        return this.assignedVstName;
    }
    
    public void setAssignedVstName(String assignedVstName) {
        this.assignedVstName = assignedVstName;
    }

    public String getSpecialtyName() {
        return this.specialtyName;
    }
    
    public void setSpecialtyName(String specialtyName) {
        this.specialtyName = specialtyName;
    }
    
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }
    
    public String getGeoAreaName() {
        return this.geoAreaName;
    }
    
    public void setGeoAreaName(String geoAreaName) {
        this.geoAreaName = geoAreaName;
    }
    
    public String getInstitutionName() {
        return this.institutionName;
    }
    
    public void setInstitutionName(String institutionName) {
        this.institutionName = institutionName;
    }
    
}


