package MeditorPersistence;
// Generated Apr 29, 2016 4:36:30 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ExtraVisit generated by hbm2java
 */
public class ExtraVisit  implements java.io.Serializable {


     private Integer id;
     private Integer doctorId;
     private Integer visitorId;
     private Integer visitOffset;
     private String status;
     private Date date;
     private Integer cycleId;

    public ExtraVisit() {
    }

    public ExtraVisit(Integer doctorId, Integer visitorId, Integer visitOffset, String status, Date date, Integer cycleId) {
       this.doctorId = doctorId;
       this.visitorId = visitorId;
       this.visitOffset = visitOffset;
       this.status = status;
       this.date = date;
       this.cycleId = cycleId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getDoctorId() {
        return this.doctorId;
    }
    
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }
    public Integer getVisitorId() {
        return this.visitorId;
    }
    
    public void setVisitorId(Integer visitorId) {
        this.visitorId = visitorId;
    }
    public Integer getVisitOffset() {
        return this.visitOffset;
    }
    
    public void setVisitOffset(Integer visitOffset) {
        this.visitOffset = visitOffset;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Integer getCycleId() {
        return this.cycleId;
    }
    
    public void setCycleId(Integer cycleId) {
        this.cycleId = cycleId;
    }




}


