package MeditorPersistence;
// Generated Apr 29, 2016 4:36:30 PM by Hibernate Tools 4.3.1



/**
 * GroupMember generated by hbm2java
 */
public class GroupMember  implements java.io.Serializable {


     private GroupMemberId id;

    public GroupMember() {
    }

    public GroupMember(GroupMemberId id) {
       this.id = id;
    }
   
    public GroupMemberId getId() {
        return this.id;
    }
    
    public void setId(GroupMemberId id) {
        this.id = id;
    }




}


