package MeditorPersistence;
// Generated Apr 29, 2016 4:36:30 PM by Hibernate Tools 4.3.1



/**
 * Group generated by hbm2java
 */
public class Group  implements java.io.Serializable {


     private Integer id;
     private Integer parentGroupId;
     private String name;
     private Integer leaderId;

    public Group() {
    }

    public Group(Integer parentGroupId, String name, Integer leaderId) {
       this.parentGroupId = parentGroupId;
       this.name = name;
       this.leaderId = leaderId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getParentGroupId() {
        return this.parentGroupId;
    }
    
    public void setParentGroupId(Integer parentGroupId) {
        this.parentGroupId = parentGroupId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getLeaderId() {
        return this.leaderId;
    }
    
    public void setLeaderId(Integer leaderId) {
        this.leaderId = leaderId;
    }




}


