package MeditorPersistence;
// Generated Apr 29, 2016 4:36:30 PM by Hibernate Tools 4.3.1



/**
 * Institution generated by hbm2java
 */
public class Institution  implements java.io.Serializable {


     private Integer id;
     private String institutionName;
     private Integer cityId;

    public Institution() {
    }

    public Institution(String institutionName, Integer cityId) {
       this.institutionName = institutionName;
       this.cityId = cityId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getInstitutionName() {
        return this.institutionName;
    }
    
    public void setInstitutionName(String institutionName) {
        this.institutionName = institutionName;
    }
    public Integer getCityId() {
        return this.cityId;
    }
    
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }




}


