package MeditorPersistence;
// Generated Apr 29, 2016 4:36:30 PM by Hibernate Tools 4.3.1



/**
 * ScheduledDoctor generated by hbm2java
 */
public class ScheduledDoctor  implements java.io.Serializable {


     private Integer id;
     private Integer doctorId;
     private Integer cycleId;
     private String numberOfApnts;

    public ScheduledDoctor() {
    }

    public ScheduledDoctor(Integer doctorId, Integer cycleId, String numberOfApnts) {
       this.doctorId = doctorId;
       this.cycleId = cycleId;
       this.numberOfApnts = numberOfApnts;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getDoctorId() {
        return this.doctorId;
    }
    
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }
    public Integer getCycleId() {
        return this.cycleId;
    }
    
    public void setCycleId(Integer cycleId) {
        this.cycleId = cycleId;
    }
    public String getNumberOfApnts() {
        return this.numberOfApnts;
    }
    
    public void setNumberOfApnts(String numberOfApnts) {
        this.numberOfApnts = numberOfApnts;
    }




}


