package MeditorPersistence;
// Generated Apr 17, 2016 9:39:15 PM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private UserId id;
     private Integer visitId;
     private Integer adminId;

    public User() {
    }

	
    public User(UserId id) {
        this.id = id;
    }
    public User(UserId id, Integer visitId, Integer adminId) {
       this.id = id;
       this.visitId = visitId;
       this.adminId = adminId;
    }
   
    public UserId getId() {
        return this.id;
    }
    
    public void setId(UserId id) {
        this.id = id;
    }
    public Integer getVisitId() {
        return this.visitId;
    }
    
    public void setVisitId(Integer visitId) {
        this.visitId = visitId;
    }
    public Integer getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }




}


