package MeditorPersistence;
// Generated Apr 19, 2016 12:29:41 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserType generated by hbm2java
 */
@Entity
@Table(name="User_Type"
    ,catalog="meditorDb"
)
public class UserType  implements java.io.Serializable {


     private Integer id;
     private String usrType;

    public UserType() {
    }

    public UserType(String usrType) {
       this.usrType = usrType;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="usr_type", nullable=false, length=20)
    public String getUsrType() {
        return this.usrType;
    }
    
    public void setUsrType(String usrType) {
        this.usrType = usrType;
    }




}


