package MeditorPersistence;
// Generated Apr 29, 2016 4:36:30 PM by Hibernate Tools 4.3.1



/**
 * Visitor generated by hbm2java
 */
public class Visitor extends User  implements java.io.Serializable {


     private Integer id;
     private int userId;
     private String visitorLevel;
     private Integer superiorId;

    public Visitor() {
    }

	
    public Visitor(int userId, String visitorLevel) {
        this.userId = userId;
        this.visitorLevel = visitorLevel;
    }
    public Visitor(int userId, String visitorLevel, Integer superiorId) {
       this.userId = userId;
       this.visitorLevel = visitorLevel;
       this.superiorId = superiorId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getVisitorLevel() {
        return this.visitorLevel;
    }
    
    public void setVisitorLevel(String visitorLevel) {
        this.visitorLevel = visitorLevel;
    }
    public Integer getSuperiorId() {
        return this.superiorId;
    }
    
    public void setSuperiorId(Integer superiorId) {
        this.superiorId = superiorId;
    }




}


