package MeditorPersistence;
// Generated Apr 19, 2016 12:29:41 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Visitor generated by hbm2java
 */
@Entity
@Table(name="Visitor"
    ,catalog="meditorDb"
    , uniqueConstraints = @UniqueConstraint(columnNames="user_id") 
)
public class Visitor  implements java.io.Serializable {


     private Integer id;
     private int userId;
     private String visitorLevel;

    public Visitor() {
    }

    public Visitor(int userId, String visitorLevel) {
       this.userId = userId;
       this.visitorLevel = visitorLevel;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="user_id", unique=true, nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

    
    @Column(name="visitor_level", nullable=false, length=50)
    public String getVisitorLevel() {
        return this.visitorLevel;
    }
    
    public void setVisitorLevel(String visitorLevel) {
        this.visitorLevel = visitorLevel;
    }




}


